[project]
name = "mlops-cours"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.103",
    "dvc[s3]>=2.1.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.10.6",
    "mlflow>=3.16.1",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
    "scikit-learn>=1.9.1",
]

[project.scripts]
mlops-cours = "mlops_cours:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
